
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: db-storage-claim
    namespace: vltk8s
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi

---

kind: PersistentVolume
apiVersion: v1
metadata:
    name: db-storage
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 2Gi
    hostPath:
        path: "/data/vltk8s/"