
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: db-storage-claim
    namespace: vltk8s
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 2Gi
    selector:
        matchLabels:
            name: db-storage-production