apiVersion: apps/v1
kind: StatefulSet

metadata:
  creationTimestamp: null
  labels:
    app: tfa-database
  name: tf-database
  namespace: vltk8s

spec:
  replicas: 1
  serviceName: tfa-database
  
  updateStrategy:
    type: OnDelete

  selector:
    matchLabels:
      app: tfa-database

  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "vltk8s"
        vault.hashicorp.com/agent-inject-secret-configs: "kv/data/database/config"
        vault.hashicorp.com/agent-inject-template-configs: |
          {{ with secret "kv/data/database/config" -}}
          {{ range $k, $v := .Data.data }}
          {{ $k }}={{ $v }}
          {{ end }}
          {{- end }}
      creationTimestamp: null
      labels:
        app: tfa-database
    spec:
      serviceAccountName: vltk8s-service-acct
    
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-storage-claim

      containers:
        - name: tfa-database
          image: postgres:9.5-alpine
          imagePullPolicy: IfNotPresent
          envFrom:
          - configMapRef:
              name: postgres-config

          ports:
            - containerPort: 5432

      restartPolicy: Always
